mitarashi-webcamp/NaganoCake

README.md
deviseのインストールおよびモデル(customerとadmin)の追加
=> install-devise

app/models/cart.rb, app/models/delivery_address.rb, app/models/genre.rb, app/models/order.rb, app/models/order_product.rb, app/models/product.rb, db/migrate/20221017090112_devise_create_customers.rb, db/migrate/20221017103946_create_delivery_addresses.rb, db/migrate/20221017104025_create_carts.rb, db/migrate/20221017104043_create_orders.rb, db/migrate/20221017104109_create_products.rb, db/migrate/20221017104124_create_order_products.rb, db/migrate/20221017104135_create_genres.rb, test/fixtures/carts.yml, test/fixtures/delivery_addresses.yml, test/fixtures/genres.yml, test/fixtures/order_products.yml, test/fixtures/orders.yml, test/fixtures/products.yml, test/models/cart_test.rb, test/models/delivery_address_test.rb, test/models/genre_test.rb, test/models/order_product_test.rb, test/models/order_test.rb, test/models/product_test.rb
=> generate-model

app/views/public/homes/top.html.erb, app/views/public/registrations/new.html.erb
=> Public registrations new

app/views/public/customers/show.html.erb
=> Add Customer Show

app/controllers/admin/products_controller.rb, app/controllers/admin/sessions_controller.rb, app/views/admin/products/index.html.erb, app/views/admin/sessions/new.html.erb, app/views/layouts/_admin_header.html.erb, app/views/layouts/application.html.erb
=> admin_header,products_index

app/controllers/admin/genres_controller.rb, app/controllers/admin/products_controller.rb, app/models/product.rb, app/views/admin/genres/index.html.erb, app/views/admin/products/_form.html.erb, app/views/admin/products/new.html.erb, app/views/admin/products/show.html.erb
プロダクトshow画面追加、コントローラ記述
プロダクトモデルに税抜価格メソッド追加
=> [Add]show_products

app/controllers/admin/genres_controller.rb, app/views/admin/genres/_form.html.erb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb
=> [Add]genres

app/controllers/concerns/application_controller.rb, app/controllers/public/customers_controller.rb
=> Customer edit

app/controllers/concerns/application_controller.rb, app/controllers/public/registrations_controller.rb, app/views/public/customers/comfirm.html.erb, app/views/public/registrations/edit.html.erb, config/routes.rb
=> customer-edit

app/controllers/admin/products_controller.rb, app/views/admin/products/_form.html.erb, app/views/admin/products/edit.html.erb, app/views/admin/products/show.html.erb, db/schema.rb
=> [Add]edit_products

app/controllers/concerns/application_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/homes_controller.rb, app/models/customer.rb, app/views/public/customers/comfirm.html.erb, app/views/public/customers/confirm.html.erb, app/views/public/homes/top.html.erb, app/views/public/registrations/edit.html.erb, app/views/public/sessions/new.html.erb, config/routes.rb
=> withdrawal-screen

app/controllers/public/delivery_addresses_controller.rb, app/views/public/delivery_addresses/edit.html.erb, app/views/public/delivery_addresses/index.html.erb
=> Add editer

app/controllers/public/delivery_addresses_controller.rb
=> Add Delete Function

app/controllers/public/customers_controller.rb, app/controllers/public/sessions_controller.rb, app/models/customer.rb
退会機能の修正
退会後のアカウントにログインしようとすると新規登録画面に遷移
=> Fix-withdrawal

app/models/cart.rb, app/models/customer.rb, app/models/delivery_address.rb, app/models/order.rb, app/models/order_product.rb, app/models/product.rb
=> Add associate

app/controllers/public/carts_controller.rb, app/controllers/public/homes_controller.rb, app/controllers/public/products_controller.rb, app/models/product.rb, app/views/public/carts/index.html.erb, app/views/public/products/show.html.erb
=> Public product show

app/views/admin/products/index.html.erb
=> index-products-UI

app/views/admin/products/_form.html.erb, app/views/admin/products/new.html.erb
=> new-product-UI

app/views/admin/products/show.html.erb
=> show-product-UI

app/views/admin/products/edit.html.erb
商品編集ページのUI
商品新規登録画面とformを共有しています。
事前にnew-product-UIをマージするようにしてください。
=> edit-product-UI

app/views/admin/genres/_form.html.erb, app/views/admin/genres/index.html.erb
=> index-genre-UI

app/views/admin/genres/edit.html.erb
ジャンル編集ページのUI
ジャンル一覧ページとformを共有しています。
正常に表示するためにはジャンル一覧ページを先にマージするようにしてください。
=> edit-genre-UI

Gemfile, Gemfile.lock, app/controllers/admin/customers_controller.rb, app/views/admin/customers/index.html.erb
=> index-customer-Pagenation

app/controllers/admin/products_controller.rb, app/views/admin/products/index.html.erb
=> index-product-Pagenation

app/controllers/public/homes_controller.rb, app/views/public/homes/top.html.erb
=> public-top

app/views/admin/customers/show.html.erb
=> show-customer-UI

app/controllers/public/products_controller.rb, app/views/public/products/index.html.erb
=> index-products

app/views/public/homes/top.html.erb, app/views/public/products/index.html.erb, app/views/public/products/show.html.erb
=> public-show-product

app/controllers/public/orders_controller.rb, app/views/public/orders/confirm.html.erb
=> order-confirm-fixed

app/controllers/public/orders_controller.rb, app/views/public/orders/index.html.erb
=> Public order index

app/controllers/public/orders_controller.rb, app/views/public/orders/show.html.erb
=> Public order show

app/controllers/admin/order_products_controller.rb, app/controllers/admin/orders_controller.rb, app/views/admin/orders/show.html.erb
=> status-add

app/controllers/public/carts_controller.rb, app/controllers/public/orders_controller.rb, app/controllers/public/products_controller.rb, app/models/cart.rb, app/models/order.rb, app/models/product.rb, app/views/public/orders/new.html.erb, app/views/public/products/show.html.erb
=> Order complete
